config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"

  get "/values", to: "signal_values#index"

  get "/latest_value", to: "signal_values#latest_value"


  resources :realtimes, only: %i[index show]

  # TelegramWebhooksController.action_path '/telegram/bot'


  # TelegramBotController.draw do
  #   telegram_webhooks TelegramBotController
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  self.abstract_class = true
end

app/models/bot.rb
class Bot < ApplicationRecord
  belongs_to :user
end

app/models/date_dictonary.rb
class DateDictonary < ApplicationRecord
end

app/models/date_time.rb
class DateTime < ApplicationRecord
  has_many :signal_values
end

app/models/realtime.rb
class Realtime < ApplicationRecord
  after_create_commit -> { broadcast_prepend_to "realtimes", partial: "realtimes/value", locals: { name: self }, target: "realtimes" }
  # belongs_to :signal_value, optional: true
end

app/models/signal_name.rb
class SignalName < ApplicationRecord
  # has_many :signal_values
end

app/models/signal_value.rb
class SignalValue < ApplicationRecord
  belongs_to :date_dictonary, optional: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/opcua_pools_controller.rb
class OpcuaPoolsController < ApplicationController
  require 'opcua_client'
  def index

    @opc_values = OpcuaPool.all
    @array_value = OpcuaPool.pluck(:name, :value)

    debugger



    begin
      client = OPCUAClient::Client.new
      client.connect("opc.tcp://127.0.0.1:55000") 
      debugger
      @value = OpcuaPool.new
  
      @value.value = client.read_float(2, "OPCDACLIENT.opcdaclient.Random.PsFloat1")
  
      @value.save

    rescue
      puts 'error'
    ensure
      client.disconnect
    end



  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/realtimes_controller.rb
class RealtimesController < ApplicationController
  def index
    
  end

  def show
    
  end
end

app/controllers/signal_values_controller.rb
class SignalValuesController < ApplicationController
  require 'opcua_client'
  def index

    
    @opcvalues = SignalValue.last(5)

    @sinus = SignalValue.where(type_value: "Sinus").last(10)

    @randoms = SignalValue.where(type_value: "Random").last(10)

    @turbo_value = SignalValue.last

    @goals = SignalValue.last(100)

    start_time = 1.hour.ago

    @powers = SignalValue.where(type_value: "Sinus").where("created_at >= ?", start_time)



    @data_chart= @powers.select(:created_at, :value).map { |data| [data.created_at, data.value] }.to_h


    @data_pie_chart = [["Blueberry",44],["Strawberry",23],["Banana",22]]
  
# debugger








    # respond_to do |format|
    #   format.turbo_stream do
    #     render turbo_stream: turbo_stream.replace("latest-value", partial: "signal_values/value", locals: {value: @turbo_value})
    #   end
    # end

    # debugger
  end


  def latest_value

    @value_from_db = SignalValue.last

    @value = @value_from_db.value
    # debugger
    render turbo_stream: turbo_stream.replace("last-value", partial: "signal_values/value", locals: { value: @value })



    
  end
end

app/controllers/telegram_webhooks_controller.rb
# class TelegramWebhooksController < Telegram::Bot::UpdatesController
#   def start!(*)
#     respond_with :message, text: 'Привет! Я бот для работы с энергетическими значениями.'
#   end

#   def energy_values!(*)
#     energy_values = SignalValue.last(10).map { |ev| "#{ev.type_value} #{ev.value}" }
#     if energy_values.empty?
#       respond_with :message, text: 'Нет доступных значений'
#     else
#       respond_with :message, text: energy_values.join("\n")
#     end
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/opcua_pools_helper.rb
module OpcuaPoolsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vpp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/menu' %> 

    <% flash.each do |key , value| %>
      <%= tag.div value, class: "alert alert-success #{key}", role: 'alert' %>
    <% end %>

    <div class="container-md"> 
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/realtimes/_realtime_value.html.erb
<%= tag.section do %>
  <%= realtime.name %>: <%= realtime.value %>
  <hr>
<% end %>

app/views/realtimes/_value.html.erb
<%= value %>

app/views/realtimes/index.html.erb
<%= turbo_stream_from "realtimes" %>

<div class="card my-3">
  <div class="card-header">
    Header
  </div>
  <div class="card-body">
    <h4 class="card-title">Title</h4>
    <p class="card-text">Text</p>
  </div>
  <div class="card-footer text-muted">
    Footer
  </div>
</div>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Third navbar example">
    <div class="container-fluid">
      <%= link_to 'Home', root_path, class: '' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample03">
        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
          <li class="nav-item">
            <%= link_to "OPC Values", values_path, class:'nav-link'%>
          </li>
          <li class="nav-item">
            <%= link_to "Real time", realtimes_path, class:'nav-link'%>
          </li>

        </ul>
      </div>
    </div>
</nav>

app/views/signal_values/_trends.html.erb
<div class="row">
 <canvas id="myChart" data-data="[3, 3, 3, 4, 3, 3]"></canvas>
</div>

app/views/signal_values/index.html.erb
<h1 class="display-4">Page values</h1>


<h1 class="display-6 text-center">Turbo value test: <%= @turbo_value.value %></h1>

<div class="table-responsive-md">
  <table class="table table-light">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">type</th>
        <th scope="col">value</th>
        <th scope="col">created_at</th>
      </tr>
    </thead>
    <tbody>
<% @opcvalues.each do |opc| %>
      <tr class="">
        <td scope="row"><%= opc.id %></td>
        <td><%= opc.type_value %></td>
        <td><%= opc.value %></td>
        <td><%= opc.created_at %></td>
      </tr>
<% end %>
    </tbody>
  </table>
</div>


<div class="container text-center my-3 p-3">
  <div class="row">
    <div class="col">
      <div class="table-responsive-md">
        <table class="table table-sm
        table-hover	
        table-borderless
        table-light
        align-middle">
          <thead class="table-light">
            <caption>Sinus</caption>
            <tr>
              <th>Value</th>
              <th>Created</th>
            </tr>
            </thead>
            <tbody class="table-group-divider">
              <% @sinus.each do |sinus|  %>
              <tr class="table-light" >
                <td scope="row"><%= sinus.value %></td>
                <td><%= sinus.created_at %></td>
              </tr>
              <% end %>
            </tbody>
            <tfoot>
              <div class="container-fluid my-3 p-3">
                <%= area_chart SignalValue.where(type_value: "Sinus").group_by_second(:created_at, range: 2.hour.ago..).average(:value) %>
              </div>

            </tfoot>
        </table>
      </div>
    

    </div>
    <div class="col">
            <div class="table-responsive-md">
        <table class="table table-sm
        table-hover	
        table-borderless
        table-light
        align-middle">
          <thead class="table-light">
            <caption>Random</caption>
            <tr>
              <th>Value</th>
              <th>Created</th>
            </tr>
            </thead>
            <tbody class="table-group-divider">
              <% @randoms.each do |randoms|  %>
              <tr class="table-light" >
                <td scope="row"><%= randoms.value %></td>
                <td><%= randoms.created_at %></td>
              </tr>
              <% end %>
            </tbody>
            <tfoot>
              <div class="container-fluid my-3 p-3">
                <%= area_chart SignalValue.where(type_value: "Random").group_by_minute(:created_at, range: 2.hour.ago..).average(:value) %>
              </div>

            </tfoot>
        </table>
      </div>
  
    </div>

</div>


<%= line_chart @data_chart %>



<%= pie_chart @data_pie_chart, donut: true, dataset: {backgroundColor: [
      'rgb(255, 99, 132)',
      'rgb(54, 162, 235)',
      'rgb(255, 205, 86)'
    ]} %>







<%= render '/signal_values/trends' %>

app/views/signal_values/latest_value.html.erb
<%= turbo_stream_from "signal_values" %>

<div id="last-value">
  <%= render partial: "value", locals: { value: @value } %>
</div>

<%= turbo_stream_action "signal_values.last_value", target: "last-value", track: "reload" %>